export const TYPES = {
    UPDATE_RECOMMENDATION                       : 'FEEDBACK_FORM/UPDATE_RECOMMENDATION',
    UPDATE_PATIENT_ISSUES                       : 'FEEDBACK_FORM/UPDATE_PATIENT_ISSUES',
    UPDATE_WAIT_TIME                            : 'FEEDBACK_FORM/UPDATE_WAIT_TIME',
    UPDATE_DOCTOR_LIST                          : 'FEEDBACK_FORM/UPDATE_DOCTOR_LIST',
    UPDATE_USER_REVIEW                          : 'FEEDBACK_FORM/UPDATE_USER_REVIEW',
    UPDATE_ANONYMOUS_STATUS                     : 'FEEDBACK_FORM/UPDATE_ANONYMOUS_STATUS',

    UPDATE_QUESTIONS                            : 'FEEDBACK_FORM/UPDATE_QUESTIONS',
   
    UPDATE_FORM_SUBMISSION_INITIATED            : 'FEEDBACK_FORM/UPDATE_FORM_SUBMISSION_INITIATED',
    UPDATE_FORM_SUBMITTED                       : 'FEEDBACK_FORM/UPDATE_FORM_SUBMITTED',

    UPDATE_DECENCY_CHECK                        : 'FEEDBACK_FORM/UPDATE_DECENCY_CHECK',
};
